@baseUrl = https://localhost:7284
@productId = 2779ee47-10b0-4bd7-8342-404006aa1392
### Options for Products
OPTIONS {{baseUrl}}/api/products

### Head for a specific Product
HEAD {{baseUrl}}/api/products/{{productId}}

### Options for a specific Product
GET {{baseUrl}}/api/products/{{productId}}?includeReviews=false

### Get a list of Products
GET {{baseUrl}}/api/products?page=4&pageSize=4

###
POST {{baseUrl}}/api/products
Content-Type: application/json

{
    "name": "keyboard",
    "price": 49.99
}

###
GET {{baseUrl}}/api/products/df696892-7c3d-4f65-a142-726e79749236

###
PUT {{baseUrl}}/api/products/{{productId}}
Content-Type: application/json

{
    "name": "Chocolate bar",
    "price": 3.50
}

###
PATCH {{baseUrl}}/api/products/{{productId}}
Content-Type: application/json-patch+json

[
    {
        "op": "replace",
        "path": "/price",
        "value": 2.99
    }
]

### DELETE
DELETE {{baseUrl}}/api/products/{{productId}}

###
POST {{baseUrl}}/api/products/process

@jobId = 2fd160b7-3f29-40d5-b448-55f520e8e612
###
GET {{baseUrl}}/api/products/status/{{jobId}}


### GET
GET {{baseUrl}}/api/products/csv

### GET
GET {{baseUrl}}/api/products/physical-csv-file

###
GET {{baseUrl}}/api/products/products-legacy

###
GET {{baseUrl}}/api/products/legacy-products